MNT: Make doc update workflow robust to first-time release-series
Make the documentation update workflow robust to first-time
release-series publication: make the workflow create `versions.json`
when it is missing before reading/updating it.

Fixes:
```
fatal: pathspec '26.0/' did not match any files
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.12/pathlib.py", line 1029, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1015, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [Errno 2] No such file or directory: 'versions.json'
```

raised for example in:
https://github.com/nipreps/niquery/actions/runs/26872833892/job/79254360667#step:7:34